# Generated by Django 5.2.12 on 2026-09-09 01:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_onboarding_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracking_mode',
            field=models.CharField(choices=[('solo', 'Just me'), ('couple', 'With a partner')], default='solo', help_text='Whether this person uses NightCap alone or with a partner.', max_length=16),
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('invite_code', models.CharField(db_index=True, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_partnerships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_partnership',
            },
        ),
        migrations.CreateModel(
            name='PartnershipInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_partner_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_partner_invites', to=settings.AUTH_USER_MODEL)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_invites', to='accounts.partnership')),
            ],
            options={
                'db_table': 'accounts_partnershipinvite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('partner', 'Partner')], default='owner', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.partnership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_partnershipmember',
                'constraints': [models.UniqueConstraint(fields=('partnership', 'user'), name='unique_partnership_member')],
            },
        ),
    ]
