# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevicePushToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=255, unique=True)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[("ios", "iOS"), ("android", "Android"), ("web", "Web")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_devicepushtoken",
            },
        ),
        migrations.CreateModel(
            name="PartnerNudge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_via", models.CharField(blank=True, max_length=32)),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_nudges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partnership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nudges",
                        to="accounts.partnership",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_nudges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_partnernudge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="partnernudge",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user", "date"),
                name="unique_partner_nudge_per_day",
            ),
        ),
    ]
