/**
 * Expandable emoji catalog for category display glyphs.
 * Selected values are posted as `emoji` (not `icon`) to the Django API.
 */
export const emojiCatalog: { emoji: string; label: string }[] = [
  // Money / spend
  { emoji: "💵", label: "Cash" },
  { emoji: "💰", label: "Money bag" },
  { emoji: "💳", label: "Card" },
  { emoji: "🏦", label: "Bank" },
  { emoji: "📈", label: "Chart up" },
  { emoji: "📉", label: "Chart down" },
  { emoji: "🧾", label: "Receipt" },
  { emoji: "💎", label: "Gem" },
  { emoji: "🏷️", label: "Tag" },
  { emoji: "🪙", label: "Coin" },
  // Food & drink
  { emoji: "🍔", label: "Burger" },
  { emoji: "🍕", label: "Pizza" },
  { emoji: "🌮", label: "Taco" },
  { emoji: "🌯", label: "Burrito" },
  { emoji: "🍣", label: "Sushi" },
  { emoji: "🍜", label: "Noodles" },
  { emoji: "🍝", label: "Pasta" },
  { emoji: "🥗", label: "Salad" },
  { emoji: "🍲", label: "Stew" },
  { emoji: "🍱", label: "Bento" },
  { emoji: "🥪", label: "Sandwich" },
  { emoji: "🥐", label: "Croissant" },
  { emoji: "🥖", label: "Bread" },
  { emoji: "🍎", label: "Apple" },
  { emoji: "🍌", label: "Banana" },
  { emoji: "🍓", label: "Berry" },
  { emoji: "🥑", label: "Avocado" },
  { emoji: "🥦", label: "Veggies" },
  { emoji: "🍩", label: "Donut" },
  { emoji: "🍪", label: "Cookie" },
  { emoji: "🍫", label: "Chocolate" },
  { emoji: "🍦", label: "Ice cream" },
  { emoji: "🍰", label: "Cake" },
  { emoji: "☕", label: "Coffee" },
  { emoji: "🍵", label: "Tea" },
  { emoji: "🧋", label: "Boba" },
  { emoji: "🍺", label: "Beer" },
  { emoji: "🍷", label: "Wine" },
  { emoji: "🍹", label: "Cocktail" },
  { emoji: "🥤", label: "Soda" },
  { emoji: "🧃", label: "Juice" },
  { emoji: "🛒", label: "Cart" },
  { emoji: "🏪", label: "Shop" },
  // Transport
  { emoji: "⛽", label: "Gas" },
  { emoji: "🚗", label: "Car" },
  { emoji: "🚕", label: "Taxi" },
  { emoji: "🚌", label: "Bus" },
  { emoji: "🚇", label: "Metro" },
  { emoji: "🚲", label: "Bike" },
  { emoji: "🛵", label: "Scooter" },
  { emoji: "✈️", label: "Plane" },
  { emoji: "🚆", label: "Train" },
  { emoji: "🚢", label: "Ship" },
  { emoji: "🅿️", label: "Parking" },
  { emoji: "🛠️", label: "Repair" },
  { emoji: "🔧", label: "Wrench" },
  // Home / shopping
  { emoji: "🏠", label: "Home" },
  { emoji: "🛋️", label: "Couch" },
  { emoji: "🧹", label: "Clean" },
  { emoji: "🪴", label: "Plant" },
  { emoji: "💡", label: "Lights" },
  { emoji: "📦", label: "Package" },
  { emoji: "🎁", label: "Gift" },
  { emoji: "🛍️", label: "Bags" },
  { emoji: "👕", label: "Shirt" },
  { emoji: "👗", label: "Dress" },
  { emoji: "👟", label: "Shoes" },
  { emoji: "👠", label: "Heels" },
  { emoji: "🧢", label: "Hat" },
  { emoji: "👓", label: "Glasses" },
  { emoji: "💍", label: "Ring" },
  { emoji: "⌚", label: "Watch" },
  // Health
  { emoji: "💊", label: "Meds" },
  { emoji: "🩺", label: "Doctor" },
  { emoji: "🦷", label: "Dental" },
  { emoji: "👁️", label: "Eyes" },
  { emoji: "🧬", label: "Labs" },
  { emoji: "🏥", label: "Hospital" },
  { emoji: "🩹", label: "Bandage" },
  // Fitness
  { emoji: "🏃", label: "Run" },
  { emoji: "🚶", label: "Walk" },
  { emoji: "🏋️", label: "Lift" },
  { emoji: "🚴", label: "Cycle" },
  { emoji: "🏊", label: "Swim" },
  { emoji: "🧘", label: "Yoga" },
  { emoji: "🤸", label: "Stretch" },
  { emoji: "🧗", label: "Climb" },
  { emoji: "⛷️", label: "Ski" },
  { emoji: "⚽", label: "Soccer" },
  { emoji: "🏀", label: "Basketball" },
  { emoji: "🎾", label: "Tennis" },
  { emoji: "⛳", label: "Golf" },
  { emoji: "🥊", label: "Boxing" },
  { emoji: "💃", label: "Dance" },
  { emoji: "⛹️", label: "Ball" },
  // Mind / habits
  { emoji: "📖", label: "Read" },
  { emoji: "📚", label: "Books" },
  { emoji: "📝", label: "Journal" },
  { emoji: "✍️", label: "Write" },
  { emoji: "🎓", label: "Learn" },
  { emoji: "🧠", label: "Mind" },
  { emoji: "😴", label: "Sleep" },
  { emoji: "💧", label: "Water" },
  { emoji: "🚭", label: "No smoke" },
  { emoji: "⏰", label: "Alarm" },
  { emoji: "🎯", label: "Goal" },
  { emoji: "✨", label: "Sparkle" },
  { emoji: "🙏", label: "Pray" },
  { emoji: "😌", label: "Calm" },
  { emoji: "💪", label: "Strong" },
  // Work / digital
  { emoji: "💼", label: "Work" },
  { emoji: "💻", label: "Laptop" },
  { emoji: "📱", label: "Phone" },
  { emoji: "📧", label: "Email" },
  { emoji: "🗓️", label: "Calendar" },
  { emoji: "📊", label: "Stats" },
  { emoji: "🧑‍💻", label: "Coding" },
  { emoji: "🖨️", label: "Print" },
  // Fun / social
  { emoji: "🎬", label: "Movies" },
  { emoji: "🎵", label: "Music" },
  { emoji: "🎮", label: "Games" },
  { emoji: "🎧", label: "Headphones" },
  { emoji: "🎤", label: "Mic" },
  { emoji: "🎨", label: "Art" },
  { emoji: "📷", label: "Photo" },
  { emoji: "🎉", label: "Party" },
  { emoji: "🥳", label: "Celebrate" },
  { emoji: "💬", label: "Chat" },
  { emoji: "❤️", label: "Heart" },
  { emoji: "🫶", label: "Care" },
  { emoji: "😊", label: "Smile" },
  { emoji: "😂", label: "Laugh" },
  { emoji: "😎", label: "Cool" },
  // Pets / nature
  { emoji: "🐶", label: "Dog" },
  { emoji: "🐱", label: "Cat" },
  { emoji: "🐾", label: "Paws" },
  { emoji: "🐦", label: "Bird" },
  { emoji: "🐠", label: "Fish" },
  { emoji: "🌳", label: "Tree" },
  { emoji: "🌸", label: "Flower" },
  { emoji: "☀️", label: "Sun" },
  { emoji: "🌙", label: "Moon" },
  { emoji: "⭐", label: "Star" },
  { emoji: "🔥", label: "Fire" },
  { emoji: "❄️", label: "Cold" },
  { emoji: "🌈", label: "Rainbow" },
  // Care / misc
  { emoji: "🔑", label: "Keys" },
  { emoji: "🧸", label: "Toy" },
  { emoji: "🧳", label: "Luggage" },
  { emoji: "💇", label: "Haircut" },
  { emoji: "💅", label: "Nails" },
  { emoji: "🧴", label: "Lotion" },
  { emoji: "👶", label: "Baby" },
  { emoji: "🧷", label: "Pin" },
  { emoji: "🪄", label: "Magic" },
  { emoji: "🧩", label: "Puzzle" },
];

export const emojiOptions = emojiCatalog;

/** Legacy key → emoji for seeded defaults / groups. Never display raw keys in UI. */
export const emojiByKey: Record<string, string> = {
  // Groups
  spend: "💵",
  follow_up: "✨",
  // Categories
  fast_food: "🍔",
  eating_out: "🍽️",
  food_deliveries: "🛵",
  groceries: "🛒",
  car_gas: "⛽",
  car_repair: "🔧",
  house_supplies: "🧴",
  clothes: "👕",
  gifts: "🎁",
  coffee: "☕",
  walks: "🚶",
  misc: "🧾",
  fuelpump: "⛽",
  wineglass: "🍷",
  drop: "💧",
  "figure.run": "🏃",
  "figure.strengthtraining.traditional": "💪",
  "figure.core.training": "🤸",
  online_shopping: "🛍️",
  going_out: "🎉",
  invested: "💰",
  read: "📖",
  run_workout: "🏃",
  sauna_meditation: "🧘",
  custom: "✨",
  habit: "🎯",
};
