# Generated by Django 5.2.12 for NightCap

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("finance_expense", "Finance Expense"),
                            ("finance_income", "Finance Income"),
                            ("fitness", "Fitness"),
                            ("habit", "Habit"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=64)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tracking categories",
                "db_table": "categories_trackingcategory",
                "ordering": ["type", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="trackingcategory",
            constraint=models.UniqueConstraint(
                fields=("user", "name", "type"),
                name="unique_category_name_type_per_user",
            ),
        ),
    ]
