# Generated by Django 5.2.12 on 2026-07-15 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_mobile_ritual_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingcategory',
            options={'ordering': ['group__sort_order', 'sort_order', 'name'], 'verbose_name_plural': 'Tracking categories'},
        ),
        migrations.AddField(
            model_name='trackingcategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CategoryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('key', models.SlugField(help_text='Stable client key, e.g. daily_spend or follow_up.', max_length=64)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('show_in_ritual', models.BooleanField(default=True, help_text='When true, this group is offered on the nightly NightCap screens.')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories_categorygroup',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='trackingcategory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='categories.categorygroup'),
        ),
        migrations.AddConstraint(
            model_name='categorygroup',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_category_group_key_per_user'),
        ),
        migrations.AddConstraint(
            model_name='categorygroup',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_group_name_per_user'),
        ),
    ]
