# Generated by Django 5.2.12 on 2026-07-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_groups_and_nightcap'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingcategory',
            name='emoji',
            field=models.CharField(blank=True, default='', help_text='Display emoji saved for this category (e.g. 🛒).', max_length=16),
        ),
        migrations.AlterField(
            model_name='trackingcategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Optional stable glyph key for clients (e.g. groceries).', max_length=64),
        ),
    ]
