# Generated by Django 5.2.12 on 2026-09-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_rename_follow_up_group_to_health'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='key',
            field=models.SlugField(help_text='Stable client key, e.g. daily_spend or follow_up (Health group).', max_length=64),
        ),
    ]
