# Generated by Django 5.2.12 on 2026-09-09 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_couple_habits_onboarding'),
        ('goals', '0004_one_active_goal_per_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='accounts.partnership'),
        ),
        migrations.AddField(
            model_name='goal',
            name='scope',
            field=models.CharField(choices=[('personal', 'Just me'), ('shared', 'Together')], db_index=True, default='personal', max_length=16),
        ),
        migrations.AddField(
            model_name='goal',
            name='template_slug',
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='audience',
            field=models.CharField(choices=[('personal', 'Personal'), ('couple', 'Couple'), ('both', 'Both')], default='both', max_length=16),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='category_emoji',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='category_group_key',
            field=models.SlugField(blank=True, help_text='daily_spend or follow_up. Blank = infer from category type.', max_length=64),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='suggest_couple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='suggest_solo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goaltemplate',
            name='suggested_scope',
            field=models.CharField(choices=[('personal', 'Just me'), ('shared', 'Together')], default='personal', max_length=16),
        ),
    ]
