# Generated by Django 5.2.12 on 2026-07-15 01:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_mobile_ritual_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NightCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('reflection', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'entries_nightcap',
                'ordering': ['-date'],
            },
        ),
        migrations.RenameIndex(
            model_name='entry',
            new_name='entries_ent_user_id_7c6e83_idx',
            old_name='entries_ent_user_id_9b4e73_idx',
        ),
        migrations.RenameIndex(
            model_name='entry',
            new_name='entries_ent_user_id_d49d52_idx',
            old_name='entries_ent_user_id_e305d8_idx',
        ),
        migrations.AddField(
            model_name='nightcap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nightcaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='nightcap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='entries.nightcap'),
        ),
        migrations.AddConstraint(
            model_name='nightcap',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_nightcap_per_user_date'),
        ),
    ]
