# Generated by Django 5.2.12 on 2026-07-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_seed_nightcaps_and_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightcap',
            name='mood',
            field=models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('okay', 'Okay'), ('low', 'Low'), ('rough', 'Rough')], default='', help_text='Optional end-of-day mood: great, good, okay, low, rough.', max_length=16),
        ),
    ]
