# Generated by Django 5.2.12 on 2026-07-15 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_nightcap_mood_emoji_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightcap',
            name='mood',
            field=models.CharField(blank=True, default='', help_text='End-of-day mood emoji (suggested: 🤩 🙂 😐 😔 😣; custom allowed).', max_length=32),
        ),
    ]
