# Generated by Django 5.2.12 on 2026-09-10 14:58

import django.core.validators
import entries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0009_entry_completed_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightcap',
            name='favorite_moment',
            field=models.TextField(blank=True, help_text='Favorite text moment of the day.'),
        ),
        migrations.AddField(
            model_name='nightcap',
            name='favorite_photo',
            field=models.ImageField(blank=True, help_text='Favorite photo of the day.', null=True, upload_to=entries.models.nightcap_photo_upload_to, validators=[django.core.validators.FileExtensionValidator(('jpg', 'jpeg', 'png', 'webp'))]),
        ),
    ]
