from decimal import Decimal

from categories.models import TrackingCategory
from goals.models import Goal, GoalTemplate

DEFAULT_GOAL_TEMPLATES = [
    {
        "slug": "drinks-monthly-max",
        "title": "Drinks budget",
        "description": "Keep bar, nightlife, and drink spending under a monthly cap.",
        "example_entry_label": "$12 at the bar",
        "category_name": "Drinks",
        "category_type": TrackingCategory.FINANCE_EXPENSE,
        "category_icon": "wineglass",
        "period": Goal.PERIOD_MONTHLY,
        "direction": Goal.DIRECTION_MAX,
        "target_value": Decimal("100.00"),
        "group": GoalTemplate.GROUP_FINANCE,
        "sort_order": 1,
    },
    {
        "slug": "gas-monthly-max",
        "title": "Gas spending cap",
        "description": "Stay under a monthly fuel budget.",
        "example_entry_label": "$32 at Shell",
        "category_name": "Gas",
        "category_type": TrackingCategory.FINANCE_EXPENSE,
        "category_icon": "fuelpump",
        "period": Goal.PERIOD_MONTHLY,
        "direction": Goal.DIRECTION_MAX,
        "target_value": Decimal("300.00"),
        "group": GoalTemplate.GROUP_FINANCE,
        "sort_order": 2,
    },
    {
        "slug": "eating-out-monthly-max",
        "title": "Eating out limit",
        "description": "Cap restaurants and takeout for the month.",
        "example_entry_label": "$24 at Chipotle",
        "category_name": "Eating Out",
        "category_type": TrackingCategory.FINANCE_EXPENSE,
        "category_icon": "takeoutbag.and.cup.and.straw",
        "period": Goal.PERIOD_MONTHLY,
        "direction": Goal.DIRECTION_MAX,
        "target_value": Decimal("150.00"),
        "group": GoalTemplate.GROUP_FINANCE,
        "sort_order": 3,
    },
    {
        "slug": "groceries-monthly-max",
        "title": "Groceries budget",
        "description": "Track grocery runs and stay within budget.",
        "example_entry_label": "$86 at Trader Joe's",
        "category_name": "Groceries",
        "category_type": TrackingCategory.FINANCE_EXPENSE,
        "category_icon": "cart",
        "period": Goal.PERIOD_MONTHLY,
        "direction": Goal.DIRECTION_MAX,
        "target_value": Decimal("400.00"),
        "group": GoalTemplate.GROUP_FINANCE,
        "sort_order": 4,
    },
    {
        "slug": "pushups-weekly-min",
        "title": "Weekly push-ups",
        "description": "Build consistency with a weekly rep target.",
        "example_entry_label": "25 push-ups",
        "category_name": "Push Ups",
        "category_type": TrackingCategory.FITNESS,
        "category_icon": "figure.strengthtraining.traditional",
        "period": Goal.PERIOD_WEEKLY,
        "direction": Goal.DIRECTION_MIN,
        "target_value": Decimal("100"),
        "group": GoalTemplate.GROUP_FITNESS,
        "sort_order": 1,
    },
    {
        "slug": "pushups-monthly-min",
        "title": "Monthly push-ups",
        "description": "A bigger monthly fitness challenge.",
        "example_entry_label": "30 push-ups",
        "category_name": "Push Ups",
        "category_type": TrackingCategory.FITNESS,
        "category_icon": "figure.strengthtraining.traditional",
        "period": Goal.PERIOD_MONTHLY,
        "direction": Goal.DIRECTION_MIN,
        "target_value": Decimal("400"),
        "group": GoalTemplate.GROUP_FITNESS,
        "sort_order": 2,
    },
    {
        "slug": "situps-weekly-min",
        "title": "Weekly sit-ups",
        "description": "Hit your core reps every week.",
        "example_entry_label": "30 sit-ups",
        "category_name": "Sit Ups",
        "category_type": TrackingCategory.FITNESS,
        "category_icon": "figure.core.training",
        "period": Goal.PERIOD_WEEKLY,
        "direction": Goal.DIRECTION_MIN,
        "target_value": Decimal("100"),
        "group": GoalTemplate.GROUP_FITNESS,
        "sort_order": 3,
    },
    {
        "slug": "workouts-weekly-min",
        "title": "Weekly workouts",
        "description": "Log gym sessions, runs, or home workouts.",
        "example_entry_label": "45 min workout",
        "category_name": "Workout",
        "category_type": TrackingCategory.FITNESS,
        "category_icon": "figure.run",
        "period": Goal.PERIOD_WEEKLY,
        "direction": Goal.DIRECTION_MIN,
        "target_value": Decimal("3"),
        "group": GoalTemplate.GROUP_FITNESS,
        "sort_order": 4,
    },
    {
        "slug": "water-daily-min",
        "title": "Daily water habit",
        "description": "Check in when you hit your hydration goal.",
        "example_entry_label": "8 glasses today",
        "category_name": "Water",
        "category_type": TrackingCategory.HABIT,
        "category_icon": "drop",
        "period": Goal.PERIOD_DAILY,
        "direction": Goal.DIRECTION_MIN,
        "target_value": Decimal("1"),
        "group": GoalTemplate.GROUP_HABIT,
        "sort_order": 1,
    },
]


def seed_goal_templates():
    for item in DEFAULT_GOAL_TEMPLATES:
        slug = item["slug"]
        defaults = {key: value for key, value in item.items() if key != "slug"}
        GoalTemplate.objects.update_or_create(slug=slug, defaults=defaults)
