from decimal import Decimal

from categories.models import CategoryGroup, TrackingCategory
from goals.models import Goal, GoalTemplate

# Shared helpers for template rows.
_FINANCE = TrackingCategory.FINANCE_EXPENSE
_FITNESS = TrackingCategory.FITNESS
_HABIT = TrackingCategory.HABIT
_MAX = Goal.DIRECTION_MAX
_MIN = Goal.DIRECTION_MIN
_MONTH = Goal.PERIOD_MONTHLY
_WEEK = Goal.PERIOD_WEEKLY
_DAY = Goal.PERIOD_DAILY
_SPEND = CategoryGroup.KEY_DAILY_SPEND
_FOLLOW = CategoryGroup.KEY_FOLLOW_UP


def _t(**kwargs):
    return kwargs


DEFAULT_GOAL_TEMPLATES = [
    _t(
        slug="groceries-monthly-max",
        title="Groceries budget",
        description="Stay within a grocery budget — often a household one.",
        example_entry_label="$86 at Trader Joe's",
        category_name="Groceries",
        category_type=_FINANCE,
        category_icon="groceries",
        category_emoji="🛒",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("400.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=True,
        suggest_couple=True,
        sort_order=1,
    ),
    _t(
        slug="eating-out-monthly-max",
        title="Eating out limit",
        description="Cap restaurants and takeout for the month.",
        example_entry_label="$24 at Chipotle",
        category_name="Eating Out",
        category_type=_FINANCE,
        category_icon="eating_out",
        category_emoji="🍽️",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("150.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=2,
    ),
    _t(
        slug="food-delivery-monthly-max",
        title="Food delivery cap",
        description="Keep delivery apps from running away.",
        example_entry_label="$22 DoorDash",
        category_name="Food Deliveries",
        category_type=_FINANCE,
        category_icon="food_deliveries",
        category_emoji="🛵",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("80.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=False,
        suggest_couple=True,
        sort_order=3,
    ),
    _t(
        slug="date-night-monthly-max",
        title="Date nights",
        description="A monthly budget for nights out together.",
        example_entry_label="$64 dinner + drinks",
        category_name="Date Night",
        category_type=_FINANCE,
        category_icon="going_out",
        category_emoji="🌹",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("200.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_COUPLE,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=False,
        suggest_couple=True,
        sort_order=4,
    ),
    _t(
        slug="going-out-monthly-max",
        title="Going out",
        description="Bars, shows, and nights on the town.",
        example_entry_label="$18 drinks",
        category_name="Going Out",
        category_type=_FINANCE,
        category_icon="going_out",
        category_emoji="🎉",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("120.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=True,
        suggest_couple=True,
        sort_order=5,
    ),
    _t(
        slug="drinks-monthly-max",
        title="Drinks budget",
        description="Keep bar, nightlife, and drink spending under a monthly cap.",
        example_entry_label="$12 at the bar",
        category_name="Drinks",
        category_type=_FINANCE,
        category_icon="going_out",
        category_emoji="🍻",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("100.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=6,
    ),
    _t(
        slug="coffee-monthly-max",
        title="Coffee runs",
        description="A personal cap for cafes and coffee apps.",
        example_entry_label="$6 latte",
        category_name="Coffee",
        category_type=_FINANCE,
        category_icon="coffee",
        category_emoji="☕",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("60.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=7,
    ),
    _t(
        slug="gas-monthly-max",
        title="Gas spending cap",
        description="Stay under a monthly fuel budget.",
        example_entry_label="$32 at Shell",
        category_name="Gas",
        category_type=_FINANCE,
        category_icon="car_gas",
        category_emoji="⛽",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("300.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=True,
        suggest_couple=True,
        sort_order=8,
    ),
    _t(
        slug="misc-monthly-max",
        title="Misc spending",
        description="Catch-all for anything that doesn’t fit the other chips.",
        example_entry_label="$14 random pickup",
        category_name="Misc",
        category_type=_FINANCE,
        category_icon="misc",
        category_emoji="🧾",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("100.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=True,
        suggest_couple=True,
        sort_order=9,
    ),
    _t(
        slug="household-monthly-max",
        title="Household supplies",
        description="Shared paper goods, cleaning, and home stuff.",
        example_entry_label="$24 Target run",
        category_name="House Supplies",
        category_type=_FINANCE,
        category_icon="house_supplies",
        category_emoji="🏠",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("80.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=10,
    ),
    _t(
        slug="online-shopping-monthly-max",
        title="Online shopping",
        description="A personal Amazon / retail cap.",
        example_entry_label="$29 impulse buy",
        category_name="Online Shopping",
        category_type=_FINANCE,
        category_icon="online_shopping",
        category_emoji="🛍️",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("100.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=11,
    ),
    _t(
        slug="clothes-monthly-max",
        title="Clothes",
        description="Keep clothing spend in check.",
        example_entry_label="$48 new tee",
        category_name="Clothes",
        category_type=_FINANCE,
        category_icon="clothes",
        category_emoji="👕",
        category_group_key=_SPEND,
        period=_MONTH,
        direction=_MAX,
        target_value=Decimal("75.00"),
        group=GoalTemplate.GROUP_FINANCE,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=12,
    ),
    _t(
        slug="workouts-weekly-min",
        title="Weekly workouts",
        description="Log gym sessions, runs, or home workouts.",
        example_entry_label="45 min workout",
        category_name="Workout",
        category_type=_FITNESS,
        category_icon="run_workout",
        category_emoji="🏋️",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("3"),
        group=GoalTemplate.GROUP_FITNESS,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=True,
        suggest_couple=True,
        sort_order=1,
    ),
    _t(
        slug="walks-weekly-min",
        title="Walks together",
        description="A weekly walk goal you can share.",
        example_entry_label="evening walk",
        category_name="Walks",
        category_type=_FITNESS,
        category_icon="walks",
        category_emoji="🚶",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("3"),
        group=GoalTemplate.GROUP_FITNESS,
        audience=GoalTemplate.AUDIENCE_COUPLE,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=False,
        suggest_couple=True,
        sort_order=2,
    ),
    _t(
        slug="runs-weekly-min",
        title="Weekly runs",
        description="Hit a personal run streak.",
        example_entry_label="3 km run",
        category_name="I Ran / Worked Out",
        category_type=_FITNESS,
        category_icon="run_workout",
        category_emoji="🏃",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("2"),
        group=GoalTemplate.GROUP_FITNESS,
        audience=GoalTemplate.AUDIENCE_PERSONAL,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=3,
    ),
    _t(
        slug="pushups-weekly-min",
        title="Weekly push-ups",
        description="Build consistency with a weekly rep target.",
        example_entry_label="25 push-ups",
        category_name="Push Ups",
        category_type=_FITNESS,
        category_icon="figure.strengthtraining.traditional",
        category_emoji="💪",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("100"),
        group=GoalTemplate.GROUP_FITNESS,
        audience=GoalTemplate.AUDIENCE_PERSONAL,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=4,
    ),
    _t(
        slug="pushups-monthly-min",
        title="Monthly push-ups",
        description="A bigger monthly fitness challenge.",
        example_entry_label="30 push-ups",
        category_name="Push Ups",
        category_type=_FITNESS,
        category_icon="figure.strengthtraining.traditional",
        category_emoji="💪",
        category_group_key=_FOLLOW,
        period=_MONTH,
        direction=_MIN,
        target_value=Decimal("400"),
        group=GoalTemplate.GROUP_FITNESS,
        audience=GoalTemplate.AUDIENCE_PERSONAL,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=5,
    ),
    _t(
        slug="situps-weekly-min",
        title="Weekly sit-ups",
        description="Hit your core reps every week.",
        example_entry_label="30 sit-ups",
        category_name="Sit Ups",
        category_type=_FITNESS,
        category_icon="figure.core.training",
        category_emoji="🤸",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("100"),
        group=GoalTemplate.GROUP_FITNESS,
        audience=GoalTemplate.AUDIENCE_PERSONAL,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=6,
    ),
    _t(
        slug="water-daily-min",
        title="Daily water habit",
        description="Check in when you hit your hydration goal.",
        example_entry_label="8 glasses today",
        category_name="Water",
        category_type=_HABIT,
        category_icon="drop",
        category_emoji="💧",
        category_group_key=_FOLLOW,
        period=_DAY,
        direction=_MIN,
        target_value=Decimal("1"),
        group=GoalTemplate.GROUP_HABIT,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=True,
        suggest_couple=False,
        sort_order=1,
    ),
    _t(
        slug="read-weekly-min",
        title="Reading",
        description="Minutes with a book each week.",
        example_entry_label="20 min reading",
        category_name="I Read",
        category_type=_HABIT,
        category_icon="read",
        category_emoji="📖",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("60"),
        group=GoalTemplate.GROUP_HABIT,
        audience=GoalTemplate.AUDIENCE_PERSONAL,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=True,
        suggest_couple=False,
        sort_order=2,
    ),
    _t(
        slug="meditation-weekly-min",
        title="Meditation",
        description="A few quiet sessions each week.",
        example_entry_label="evening sit",
        category_name="Sauna / Meditation",
        category_type=_HABIT,
        category_icon="sauna_meditation",
        category_emoji="🧘",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("3"),
        group=GoalTemplate.GROUP_HABIT,
        audience=GoalTemplate.AUDIENCE_PERSONAL,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=3,
    ),
    _t(
        slug="quality-time-weekly-min",
        title="Quality time",
        description="Mark evenings you actually spent together.",
        example_entry_label="uninterrupted evening",
        category_name="Quality Time",
        category_type=_HABIT,
        category_icon="sauna_meditation",
        category_emoji="💛",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("3"),
        group=GoalTemplate.GROUP_HABIT,
        audience=GoalTemplate.AUDIENCE_COUPLE,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=False,
        suggest_couple=True,
        sort_order=4,
    ),
    _t(
        slug="cook-together-weekly-min",
        title="Cook at home",
        description="Shared home-cooked meals instead of takeout.",
        example_entry_label="we cooked dinner",
        category_name="Cook at Home",
        category_type=_HABIT,
        category_icon="eating_out",
        category_emoji="🍳",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("3"),
        group=GoalTemplate.GROUP_HABIT,
        audience=GoalTemplate.AUDIENCE_COUPLE,
        suggested_scope=Goal.SCOPE_SHARED,
        suggest_solo=False,
        suggest_couple=True,
        sort_order=5,
    ),
    _t(
        slug="phone-free-weekly-min",
        title="Phone-free evenings",
        description="Evenings without scrolling in bed.",
        example_entry_label="phones away",
        category_name="Phone-free Evening",
        category_type=_HABIT,
        category_icon="sauna_meditation",
        category_emoji="📵",
        category_group_key=_FOLLOW,
        period=_WEEK,
        direction=_MIN,
        target_value=Decimal("3"),
        group=GoalTemplate.GROUP_HABIT,
        audience=GoalTemplate.AUDIENCE_BOTH,
        suggested_scope=Goal.SCOPE_PERSONAL,
        suggest_solo=False,
        suggest_couple=False,
        sort_order=6,
    ),
]


def seed_goal_templates():
    for item in DEFAULT_GOAL_TEMPLATES:
        slug = item["slug"]
        defaults = {key: value for key, value in item.items() if key != "slug"}
        GoalTemplate.objects.update_or_create(slug=slug, defaults=defaults)
